# Generated by Django 3.0.8 on 2020-08-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20200807_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeaddress',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
