# Generated by Django 3.0.8 on 2020-08-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_homeaddress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
