# Generated by Django 3.0.8 on 2020-08-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
    ]
