# Generated by Django 3.0.8 on 2020-08-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_auto_20200822_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='phone',
        ),
    ]
