# Generated by Django 3.0.8 on 2020-08-25 03:24

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_pickup_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='citizenship',
        ),
        migrations.AddField(
            model_name='profile',
            name='business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
