# Generated by Django 3.0.8 on 2020-08-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('JM', 'Jamaica'), ('TT', 'Trinidad and Tobago'), ('US', 'United States of America'), ('CA', 'Canada'), ('OT', 'Other')], max_length=50, null=True),
        ),
    ]
