# Generated by Django 3.0.8 on 2020-08-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0017_auto_20200826_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='hcountry',
        ),
    ]
