# Generated by Django 3.0.8 on 2020-09-06 21:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0018_auto_20200826_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hcountry',
        ),
        migrations.AddField(
            model_name='profile',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homeaddress',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/%Y/%m/%d/'),
        ),
    ]
