# Generated by Django 3.0.8 on 2020-09-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20200831_1641'),
        ('seller', '0020_auto_20200907_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vouches',
        ),
        migrations.AddField(
            model_name='profile',
            name='vouches',
            field=models.ManyToManyField(to='store.Customer'),
        ),
    ]
