# Generated by Django 3.0.8 on 2020-09-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0021_auto_20200907_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tier_points',
            field=models.IntegerField(default=0),
        ),
    ]
