# Generated by Django 3.0.8 on 2020-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0022_profile_tier_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('T0', 'Tier 0'), ('T1', 'Tier 1'), ('T2', 'Tier 2'), ('T3', 'Tier 3')], max_length=50, null=True),
        ),
    ]
