# Generated by Django 3.0.8 on 2020-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0024_auto_20200912_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profilepics/defaultpropic.png', null=True, upload_to='profilepics/%Y/%m/%d/'),
        ),
    ]
