# Generated by Django 3.0.8 on 2020-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0025_auto_20200912_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profilepics/defaultpropic.svg', null=True, upload_to='profilepics/%Y/%m/%d/'),
        ),
    ]
