# Generated by Django 3.0.8 on 2020-09-25 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20200925_1735'),
        ('seller', '0026_auto_20200912_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='store.Customer'),
        ),
    ]
