# Generated by Django 3.0.8 on 2020-10-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0027_profile_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tier',
            field=models.CharField(choices=[('T1', 'Tier 1'), ('T2', 'Tier 2'), ('T3', 'Tier 3')], default='T1', max_length=50, null=True),
        ),
    ]
