# Generated by Django 3.0.8 on 2020-07-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
