# Generated by Django 3.0.8 on 2020-08-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200815_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
