# Generated by Django 3.0.8 on 2020-08-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200819_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='singleitems',
            field=models.ManyToManyField(to='store.SingleBuy'),
        ),
    ]
