# Generated by Django 3.0.8 on 2020-08-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TB', 'textbook'), ('NB', 'notebook'), ('LB', 'literature book'), ('RB', 'reading book')], max_length=10, null=True),
        ),
    ]
