# Generated by Django 3.0.8 on 2020-08-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_pickup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pickup',
        ),
    ]
