# Generated by Django 3.0.8 on 2020-08-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_delete_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.OrderItem')),
            ],
        ),
    ]
