# Generated by Django 3.0.8 on 2020-08-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_solditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Customer'),
        ),
    ]
