# Generated by Django 3.0.8 on 2020-08-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('BN', 'Brand New'), ('UD', 'Used'), ('PC', 'Poor Condition')], max_length=200, null=True),
        ),
    ]
