# Generated by Django 3.0.8 on 2020-08-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amt_available',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
