# Generated by Django 3.0.8 on 2020-08-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_amt_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='seller',
        ),
    ]
