# Generated by Django 3.0.8 on 2020-08-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200822_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solditem',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solditem',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='solditem',
            name='product_total',
            field=models.IntegerField(default=1),
        ),
    ]
