# Generated by Django 3.0.8 on 2020-08-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200822_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
