# Generated by Django 3.0.8 on 2020-08-08 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_seller1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller1',
        ),
    ]
