# Generated by Django 3.0.8 on 2020-08-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_solditem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='product_total',
        ),
        migrations.AddField(
            model_name='product',
            name='amt_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solditem',
            name='products_left',
            field=models.IntegerField(default=0),
        ),
    ]
