# Generated by Django 3.0.8 on 2020-08-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20200822_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='purchased_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
