# Generated by Django 3.0.8 on 2020-08-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_solditem_purchased_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='re_evaluating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
