# Generated by Django 3.0.8 on 2020-08-08 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20200807_1848'),
        ('store', '0023_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.Profile'),
        ),
    ]
