# Generated by Django 3.0.8 on 2020-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_singlebuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlebuy',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
