# Generated by Django 3.0.8 on 2020-09-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20200912_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='restocking',
            field=models.BooleanField(default=False),
        ),
    ]
