# Generated by Django 3.0.8 on 2020-09-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_restocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
