# Generated by Django 3.0.8 on 2020-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20201001_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/book.svg', null=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
