# Generated by Django 3.0.8 on 2020-10-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20201001_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TB', 'Textbooks'), ('NB', 'Notebooks'), ('LB', 'Literature Books'), ('RB', 'Reading Books')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('BN', 'Brand New'), ('NGC', 'New Good Condition'), ('NPC', 'New Poor Condition'), ('UGD', 'Used Good Condition'), ('UPC', 'Used Poor Condition')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
